// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Progetto.Services;

#nullable disable

namespace Progetto.Web.Migrations
{
    [DbContext(typeof(TemplateDbContext))]
    partial class TemplateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Template.Services.BuoniDigitali.Azienda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Attiva")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitaIva")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Aziende");
                });

            modelBuilder.Entity("Template.Services.BuoniDigitali.Convenzione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Attiva")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AziendaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EsercenteId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ImportoMassimoSconto")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ImportoMinimo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxUtilizziPerDipendente")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PercentualeRemunerazione")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentualeSconto")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PeriodoGiorni")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EsercenteId");

                    b.HasIndex("AziendaId", "EsercenteId");

                    b.ToTable("Convenzioni");
                });

            modelBuilder.Entity("Template.Services.BuoniDigitali.Dipendente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AziendaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAssunzione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricola")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reparto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AziendaId");

                    b.HasIndex("UserId");

                    b.ToTable("Dipendenti");
                });

            modelBuilder.Entity("Template.Services.BuoniDigitali.Esercente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAttivita")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitaIva")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Esercenti");
                });

            modelBuilder.Entity("Template.Services.BuoniDigitali.UtilizzoConvenzione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceUtilizzo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConvenzioneId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCertificazione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRichiesta")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DipendenteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EsercenteId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImportoPagato")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImportoRemunerazione")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImportoSconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImportoTotale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoRifiuto")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodiceUtilizzo")
                        .IsUnique();

                    b.HasIndex("ConvenzioneId");

                    b.HasIndex("DipendenteId", "DataRichiesta");

                    b.HasIndex("EsercenteId", "DataRichiesta");

                    b.ToTable("UtilizziConvenzioni");
                });

            modelBuilder.Entity("Template.Services.Shared.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Template.Services.BuoniDigitali.Convenzione", b =>
                {
                    b.HasOne("Template.Services.BuoniDigitali.Azienda", "Azienda")
                        .WithMany("Convenzioni")
                        .HasForeignKey("AziendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Template.Services.BuoniDigitali.Esercente", "Esercente")
                        .WithMany("Convenzioni")
                        .HasForeignKey("EsercenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Azienda");

                    b.Navigation("Esercente");
                });

            modelBuilder.Entity("Template.Services.BuoniDigitali.Dipendente", b =>
                {
                    b.HasOne("Template.Services.BuoniDigitali.Azienda", "Azienda")
                        .WithMany("Dipendenti")
                        .HasForeignKey("AziendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Template.Services.Shared.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Azienda");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Template.Services.BuoniDigitali.Esercente", b =>
                {
                    b.HasOne("Template.Services.Shared.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Template.Services.BuoniDigitali.UtilizzoConvenzione", b =>
                {
                    b.HasOne("Template.Services.BuoniDigitali.Convenzione", "Convenzione")
                        .WithMany("Utilizzi")
                        .HasForeignKey("ConvenzioneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Template.Services.BuoniDigitali.Dipendente", "Dipendente")
                        .WithMany("UtilizziConvenzioni")
                        .HasForeignKey("DipendenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Template.Services.BuoniDigitali.Esercente", "Esercente")
                        .WithMany("UtilizziCertificati")
                        .HasForeignKey("EsercenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Convenzione");

                    b.Navigation("Dipendente");

                    b.Navigation("Esercente");
                });

            modelBuilder.Entity("Template.Services.BuoniDigitali.Azienda", b =>
                {
                    b.Navigation("Convenzioni");

                    b.Navigation("Dipendenti");
                });

            modelBuilder.Entity("Template.Services.BuoniDigitali.Convenzione", b =>
                {
                    b.Navigation("Utilizzi");
                });

            modelBuilder.Entity("Template.Services.BuoniDigitali.Dipendente", b =>
                {
                    b.Navigation("UtilizziConvenzioni");
                });

            modelBuilder.Entity("Template.Services.BuoniDigitali.Esercente", b =>
                {
                    b.Navigation("Convenzioni");

                    b.Navigation("UtilizziCertificati");
                });
#pragma warning restore 612, 618
        }
    }
}
